services:
  mcproxy:
    build:
      context: ../
      dockerfile: Dockerfile
    command: ["/config/config.toml"]
    volumes:
      - .:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # Minecraft
      - 25565:25565
      # Tokio-console
      - 6669:6669
    environment:
      TOKIO_CONSOLE_BIND: "0.0.0.0:6669"
      # OTLP_ENDPOINT: jaeger
      # - RUST_LOG=mcproxy=trace
    # depends_on:
    #   - jaeger

  # jaeger:
  #   image: jaegertracing/all-in-one:1.58
  #   ports:
  #     - 4317:4317
  #     - 16686:16686

  mc:
    image: itzg/minecraft-server:java21-alpine
    deploy:
      replicas: 5
      resources:
        reservations:
          cpus: 1.0
          memory: 50M
        limits:
          cpus: 2.0
          memory: 1G
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "paper"
    volumes:
      - ./pack.png:/data/server-icon.png:ro
    ports:
      - 25570-25579:25565
    labels:
      mcproxy: mcproxy.dusterthefirst.com
      mcproxy.replica_behavior: index-subdomain
      # mcproxy.port: 25565