"$schema" = "../target/schema/config.schema.json"

# [ui]
# listen_address = "127.0.0.1:9876"

# [discovery.docker]
# socket = "/var/run/docker.sock"

# A map of server addresses
[static_servers]
# "0.mcproxy.dusterthefirst.com" = "127.0.0.1:25570"
# "1.mcproxy.dusterthefirst.com" = "127.0.0.1:25571"
# "2.mcproxy.dusterthefirst.com" = "127.0.0.1:25572"
# "3.mcproxy.dusterthefirst.com" = "127.0.0.1:25573"
# "4.mcproxy.dusterthefirst.com" = "127.0.0.1:25574"
# "5.mcproxy.dusterthefirst.com" = "127.0.0.1:25575"
"localhost" = "127.0.0.1:25570" # FIXME: loops are possible, keep track of recurse?

# Configuration for the proxy server
[proxy]
# Address to bind the Minecraft proxy to
listen_address = "0.0.0.0:25565"

[placeholder_server.responses]
# The file (if any) to the config of the response to send when a server cannot be connected to
offline = "./placeholder_servers/offline.toml"
# The file (if any) to the config of the response to send when there is no server mapping found
no_mapping = "./placeholder_servers/no_mapping.toml"
