[package]
name = "mcproxy"
version = "0.1.0"
authors = ["DusterTheFirst <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

# [lib]
# name = "mcproxy"
# path = "src/lib.rs"

[[bin]]
name = "mcproxy"
path = "src/bin.rs"

[dependencies]
byteorder = "1.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
humantime = "2.0"
ansi_term = "0.12"
async-std = { version = "1.5", features = ["attributes", "unstable"] }
argh = "0.1"
async-trait = "0.1"
