[package]
name = "mcproxy"
version = "0.1.0"
authors = ["DusterTheFirst <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

# [lib]
# name = "mcproxy"
# path = "src/lib.rs"

[[bin]]
name = "mcproxy"
path = "src/bin.rs"

[dependencies]
byteorder = "1.3.2"
serde_json = "1.0.40"
serde = { version = "1.0.99", features = ["derive"] }
humantime = "1.2.0"
ansi_term = "0.11.0"