[package]
authors = ["DusterTheFirst <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2021"
name    = "mcproxy"
version = "0.1.0"

# [lib]
# name = "mcproxy"
# path = "src/lib.rs"

[[bin]]
name = "mcproxy"
path = "src/bin.rs"

[features]
tokio-console = ["dep:console-subscriber"]

[dependencies]
base64                             = "0.22.1"
console-subscriber                 = { version = "0.3.0", optional = true }
opentelemetry                      = "0.23.0"
opentelemetry-otlp = "0.16.0"
opentelemetry-semantic-conventions = "0.15.0"
opentelemetry-stdout               = "0.4.0"
opentelemetry_sdk                  = { version = "0.23.0", features = ["rt-tokio"] }
serde                              = { version = "1.0", features = ["derive"] }
serde_json                         = "1.0"
tokio                              = { version = "1.38.0", features = ["full", "macros"] }
toml                               = "0.8.14"
tracing                            = "0.1.40"
tracing-error                      = { version = "0.2.0", features = ["traced-error"] }
tracing-opentelemetry              = "0.24.0"
tracing-subscriber                 = { version = "0.3.18", features = ["env-filter"] }
