[package]
name = "mcproxy"
version = "0.1.0"
authors = ["DusterTheFirst <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2021"

# [lib]
# name = "mcproxy"
# path = "src/lib.rs"

[[bin]]
name = "mcproxy"
path = "src/bin.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
humantime = "2.0"
ansi_term = "0.12"
argh = "0.1"
async-trait = "0.1"
toml = "0.8.14"
base64 = "0.22.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.38.0", features = ["full", "macros"] }
