"$schema" = "../../../target/schema/response.schema.json"

# The favicon to show
favicon = "../StructureVoidNew.png"

# The version to broadcast to the querying server
[version]
# The version name to show on hover
name = "Server does not exist"
# The protocol version
protocol = 0

# The players listing
[players]
# The maximum player count
max = 0
# The online player count
online = 0

# The list of players to show on hover
[[players.sample]]
# The "player" name
id   = "00000000-0000-0000-0000-000000000000"
name = "ยง4No server exists under this domain"

[[players.sample]]
id   = "00000000-0000-0000-0000-000000000000"
name = "ยง9Check your spelling and try again"

# The MOTD
[description]
# The text
text = "[mcproxy]"
# The color of the text
color = "red"

# Other components
[[description.extra]]
bold  = true
color = "dark_red"
text  = " Server not found\n"

[[description.extra]]
color  = "gold"
italic = true
text   = "Contact your server administrator for assistance"
