"$schema" = "../../../target/schema/response.schema.json"

# The favicon to show
favicon = "../BarrierNew.png"

# The version to broadcast to the querying server
[version]
# The version name to show on hover
name = "Server offline"
# The protocol version
protocol = 0

# The players listing
[players]
# The maximum player count
max = 0
# The online player count
online = 0

# The list of players to show on hover
[[players.sample]]
id   = "00000000-0000-0000-0000-000000000000"
name = "ยง4Can't connect to the server."

[[players.sample]]
id   = "00000000-0000-0000-0000-000000000000"
name = "ยง9The server may be offline."

# The MOTD
[description]
# The text
text = "[mcproxy]"
# The color of the text
color = "red"

# Other components
[[description.extra]]
bold  = true
color = "dark_red"
text  = " Can't connect to the server.\n"

[[description.extra]]
color  = "gold"
italic = true
text   = "Contact your server administrator for assistance"
