name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose
  clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run clippy
      run: cargo clippy --verbose
   rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Run rustfmt
      run: cargo fmt -- --check
