name: Test

on: [push, pull_request]

jobs:
  # Build the program
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
  # Test the program (after build)
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose
  # Lint the program (after build)
  clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Run clippy
      run: cargo clippy --verbose
  # Check code formatting (after build)
  rustfmt:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Check Rust formatting
      run: cargo fmt -- --check
  # Build and upload artifacts
  artifacts-windows:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v1
      - name: Build 64 bit Windows GNU
        run: cargo build --verbose --release --target x86_64-pc-windows-gnu
      - run: mv target/release/mcproxy target/release/mcproxy-windows-x64
        uses: actions/upload-artifact@master
        with:
          name: mcproxy-windows-x32
          path: target/release
      - name: Build 32 bit Windows GNU
        run: cargo build --verbose --release --target i686-pc-windows-gnu
      - run: mv target/release/mcproxy target/release/mcproxy-windows-x32
        uses: actions/upload-artifact@master
        with:
          name: mcproxy-windows-x32
          path: target/release
  artifacts-macos:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v1
      - name: Build 64 bit Apple Darwin
        run: cargo build --verbose --release --target x86_64-apple-darwin
      - run: mv target/release/mcproxy target/release/mcproxy-apple-x64
        uses: actions/upload-artifact@master
        with:
          name: mcproxy-apple-x64
          path: target/release
      - name: Build 32 bit Apple Darwin
        run: cargo build --verbose --release --target i686-apple-darwin
      - run: mv target/release/mcproxy target/release/mcproxy-apple-x32
        uses: actions/upload-artifact@master
        with:
          name: mcproxy-apple-x32
          path: target/release
  artifacts-linux:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v1
      - name: Build 64 bit Linux GNU
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
      - run: mv target/release/mcproxy target/release/mcproxy-linux-x64
        uses: actions/upload-artifact@master
        with:
          name: mcproxy-linux-x64
          path: target/release
      - name: Build 32 bit Linux GNU
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
      - run: mv target/release/mcproxy target/release/mcproxy-linux-x32
        uses: actions/upload-artifact@master
        with:
          name: mcproxy-linux-x32
          path: target/release
      - name: Build aarch Linux GNU
        run: cargo build --verbose --release --target aarch-unknown-linux-gnu
      - run: mv target/release/mcproxy target/release/mcproxy-linux-aarch
        uses: actions/upload-artifact@master
        with:
          name: mcproxy-linux-aarch
          path: target/release
