name: Test

on: [push, pull_request]

jobs:
  # Build the program
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
  # Test the program (after build)
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose
  # Lint the program (after build)
  clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Run clippy
      run: cargo clippy --verbose
  # Check code formatting (after build)
  rustfmt:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Check Rust formatting
      run: cargo fmt -- --check
  # Build and upload artifacts
  artifacts-windows:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v1
      - name: Add targets
        run: rustup target add x86_64-pc-windows-gnu i686-pc-windows-gnu
      - name: Build 64 bit Windows GNU
        run: cargo build --verbose --release --target x86_64-pc-windows-gnu
      - name: Rename file
        run: mv target/x86_64-pc-windows-gnu/release/mcproxy target/x86_64-pc-windows-gnu/release/mcproxy-windows-x64
      - uses: actions/upload-artifact@master
        with:
          name: mcproxy-windows-x32
          path: target/x86_64-pc-windows-gnu/release
      - name: Build 32 bit Windows GNU
        run: cargo build --verbose --release --target i686-pc-windows-gnu
      - name: Rename file
        run: mv target/i686-pc-windows-gnu/release/mcproxy target/i686-pc-windows-gnu/release/mcproxy-windows-x32
      - uses: actions/upload-artifact@master
        with:
          name: mcproxy-windows-x32
          path: target/i686-pc-windows-gnu/release
  artifacts-macos:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v1
      - name: Add targets
        run: rustup target add x86_64-apple-darwin i686-apple-darwin
      - name: Build 64 bit Apple Darwin
        run: cargo build --verbose --release --target x86_64-apple-darwin
      - name: Rename file
        run: mv target/x86_64-apple-darwin/release/mcproxy target/x86_64-apple-darwin/release/mcproxy-apple-x64
      - uses: actions/upload-artifact@master
        with:
          name: mcproxy-apple-x64
          path: target/x86_64-apple-darwin/release
      - name: Build 32 bit Apple Darwin
        run: cargo build --verbose --release --target i686-apple-darwin
      - name: Rename file
        run: mv target/i686-apple-darwin/release/mcproxy target/i686-apple-darwin/release/mcproxy-apple-x32
      - uses: actions/upload-artifact@master
        with:
          name: mcproxy-apple-x32
          path: target/i686-apple-darwin/release
  artifacts-linux:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v1
      - name: Add targets
        run: rustup target add x86_64-unknown-linux-gnu i686-unknown-linux-gnu aarch-unknown-linux-gnu
      - name: Build 64 bit Linux GNU
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
      - name: Rename file
        run: mv target/x86_64-unknown-linux-gnu/release/mcproxy target/x86_64-unknown-linux-gnu/release/mcproxy-linux-x64
      - uses: actions/upload-artifact@master
        with:
          name: mcproxy-linux-x64
          path: target/x86_64-unknown-linux-gnu/release
      - name: Build 32 bit Linux GNU
        run: cargo build --verbose --release --target i686-unknown-linux-gnu
      - name: Rename file
        run: mv target/i686-unknown-linux-gnu/release/mcproxy target/i686-unknown-linux-gnu/release/mcproxy-linux-x32
      - uses: actions/upload-artifact@master
        with:
          name: mcproxy-linux-x32
          path: target/i686-unknown-linux-gnu/release
      - name: Build aarch Linux GNU
        run: cargo build --verbose --release --target aarch-unknown-linux-gnu
      - name: Rename file
        run: mv target/aarch-unknown-linux-gnu/release/mcproxy target/aarch-unknown-linux-gnu/release/mcproxy-linux-aarch
      - uses: actions/upload-artifact@master
        with:
          name: mcproxy-linux-aarch
          path: target/aarch-unknown-linux-gnu/release
